[tool.poetry]
name = "bnss"
version = "0.1.0"
description = "Music bot for Discord written in Python"
authors = ["atbuy <contact.atbuy@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"
discord-py = {version = "^2.3.1", extras = ["voice"]}
pydantic-settings = "^2.0.2"
yt-dlp = "^2023.7.6"


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
isort = "^5.12.0"
flake8 = "^6.1.0"
pre-commit = "^3.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
